name: 'Java Custom Action'
description: 'Running my java code'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run Java Code
      shell: bash
      run: |
        javac Main.java
        java Main